version: '3'
services:
  postgres:
    image: postgres:14
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: player_user
      POSTGRES_PASSWORD: player_user_password
      POSTGRES_DB: player
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U player_user" ]
      interval: 30s
      timeout: 10s
      retries: 5

  rest-service:
    build:
      context: ./rest-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/player
      SPRING_DATASOURCE_USERNAME: player_user
      SPRING_DATASOURCE_PASSWORD: player_user_password

volumes:
  database:
