services:
  postgres:
    image: postgres:14
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dokolist

  rest-service:
    build:
      context: ./rest-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dokolist
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


  doko-app:
    build:
      context: ./doko-app
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    depends_on:
      - rest-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080/api


volumes:
  database:
